### ISSUE TITLE
Create site with easy (automatic) deployment

### ISSUE THREAD

**Issue by Walther** [Walther/verbose-pancake#16]
Estimated time: 2 h

**Comment by Walther** [comment]
Suggestion: Heroku?

**Comment by Walther** [comment]
Decided on heroku, app deployed to [here](https://verbose-pancake.herokuapp.com/). No automatic deployment for now.

**Comment by Walther** [comment]
Automatic deployment enabled at 1f654e6

**Comment by odeporkka** [comment]
Priority: High
