### ISSUE TITLE
Cannot GET /bibtex-list through in web deployed version

### ISSUE THREAD

**Issue by ghost** [Walther/verbose-pancake#27]
http://verbose-pancake.herokuapp.com/bibtex-list returns:

> > Application Error
> > An error occurred in the application and your page could not be served. Please try again in a few moments.
> > 
> > If you are the application owner, check your logs for details.

TODO: check logs, I guess the problem is either with a path (in bibtexify.py it's assumed that /data is in the same directory as the script is) or with the response format (plain text)

Estimated time: 1 h

**Comment by odeporkka** [comment]
Priority: Medium
