### ISSUE TITLE
Cannot add citations

### ISSUE THREAD

**Issue by Walther** [Walther/verbose-pancake#3]
> viitteitä pitää pystyä lisäämään järjestelmään ihmiselle hyvässä muodossa, esimerkiksi jonkun lomakkeen avulla.
> esim. ääkköset pitää toimia kunnolla, ei saa joutua lisäämään hankalassa muodossa kuten yllä, samoin kirjainlyhenteet

Users want the ability to add citations into the system.
Requirements:
- Form with input fields
- Author(s)
- Title
- Source article
- Page(s)
- Publisher(s)

NOTE: Initial scope includes only supporting Articles. Optional features later: book, journal...

Estimated time: 2 h

**Comment by Walther** [comment]
depends on issue #16

**Comment by Walther** [comment]
fixed at 5c1d67f33665acfe237850bb53b612c7099a2e50

**Comment by odeporkka** [comment]
Priority: High
