### ISSUE TITLE
Additional formats for entries

### ISSUE THREAD

**Issue by Kargamborgh** [Walther/verbose-pancake#36]
Current supported formats are book, article, inproceedings: additional formats required

**Comment by ghost** [comment]
Which additional formats, did anyone get any hint from the live meeting or are they optional?

Though the bibtex formatter is agnostic to any format as long as JSON input follows the contract

**Comment by Walther** [comment]
Maybe check which ones are most popular / common and pick two/three?

**Comment by Walther** [comment]
9890b20aba8c7cd51eade4db2f407803b87dc053
