### ISSUE TITLE
Cannot generate BibTeX

### ISSUE THREAD

**Issue by Walther** [Walther/verbose-pancake#4]
> järjestelmässä olevista viitteistä pitää saada generoitua LaTeX-dokumenttiin sopiva BibTeX-muotoinen tiedosto

Users want the ability to generate a BibTeX file from the citations in the system.

Estimated time: 2 h

**Comment by Kargamborgh** [comment]
BibTeX should work together with LaTeX: customer requested formats article, book, inproceedings

**Comment by ghost** [comment]
Now it's possible to generate a BibTeX file from the fields that are in the form

I'll do new issues for generating BibTeX for different formats

**Comment by odeporkka** [comment]
Priority: Very High
