### ISSUE TITLE
Cannot list citations

### ISSUE THREAD

**Issue by Walther** [Walther/verbose-pancake#5]
> myös viitteiden listaaminen ihmiselle sopivammassa formaatissa pitää onnistua

Users want a human-readable view of the current citation list.

Requirements:
- Human-readable
- Easy to view

Estimated time: 2 h

**Comment by Walther** [comment]
depends on issue #16

**Comment by Walther** [comment]
fixed at 5c1d67f33665acfe237850bb53b612c7099a2e50

**Comment by odeporkka** [comment]
Priority: High
